#!/usr/bin/env bash
# Bootstrap Postgres 16 + Redis on a dedicated data host (multi-host Sinexis).
# Run ON the data VPS as a sudo-capable user. Does not print secrets to stdout
# after generation (writes a local credentials file mode 600).
#
# Usage:
#   APP_HOST_CIDR=x.x.x.x/32 ./scripts/bootstrap-data-host.sh
#   APP_HOST_CIDR=x.x.x.x/32 DATA_PUBLIC_HOST=y.y.y.y ./scripts/bootstrap-data-host.sh
#
# Env:
#   APP_HOST_CIDR   required — app host IP/CIDR allowed to reach 5432/6379 (ufw)
#   DATA_PUBLIC_HOST optional — host/IP app will use in URLs (default: detect)
#   POSTGRES_DB / POSTGRES_USER — defaults vuln_scanner
#   CRED_FILE — default $HOME/sinexis-data-credentials.env (NOT for git)
#
# Safe to re-run: keeps existing passwords in CRED_FILE if present.

set -euo pipefail

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  sed -n '2,20p' "$0" | sed 's/^# \?//'
  exit 0
fi

if [[ "$(id -u)" -eq 0 ]]; then
  echo "error: run as normal user with sudo (not as root)" >&2
  exit 1
fi

APP_HOST_CIDR="${APP_HOST_CIDR:-}"
if [[ -z "$APP_HOST_CIDR" ]]; then
  echo "error: set APP_HOST_CIDR to the app host IP (e.g. 1.2.3.4/32)" >&2
  exit 1
fi

POSTGRES_DB="${POSTGRES_DB:-vuln_scanner}"
POSTGRES_USER="${POSTGRES_USER:-vuln_scanner}"
CRED_FILE="${CRED_FILE:-$HOME/sinexis-data-credentials.env}"
DATA_PUBLIC_HOST="${DATA_PUBLIC_HOST:-}"

echo "=== bootstrap data host ==="
echo "app allow: $APP_HOST_CIDR"
echo "cred file: $CRED_FILE"

export DEBIAN_FRONTEND=noninteractive

echo "=== apt: postgresql redis ufw ==="
sudo apt-get update -y
sudo apt-get install -y postgresql postgresql-contrib redis-server ufw openssl

if [[ -f "$CRED_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CRED_FILE"
  echo "reusing passwords from existing cred file"
fi

if [[ -z "${POSTGRES_PASSWORD:-}" ]]; then
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"
fi
if [[ -z "${REDIS_PASSWORD:-}" ]]; then
  REDIS_PASSWORD="$(openssl rand -hex 24)"
fi

if [[ -z "$DATA_PUBLIC_HOST" ]]; then
  DATA_PUBLIC_HOST="$(curl -4 -sS --max-time 5 ifconfig.me 2>/dev/null || true)"
fi
if [[ -z "$DATA_PUBLIC_HOST" ]]; then
  DATA_PUBLIC_HOST="$(hostname -I | awk '{print $1}')"
fi

echo "=== ufw ==="
sudo ufw allow OpenSSH
sudo ufw delete allow 5432/tcp 2>/dev/null || true
sudo ufw delete allow 6379/tcp 2>/dev/null || true
sudo ufw allow from "$APP_HOST_CIDR" to any port 5432 proto tcp comment 'sinexis-app-pg'
sudo ufw allow from "$APP_HOST_CIDR" to any port 6379 proto tcp comment 'sinexis-app-redis'
echo "y" | sudo ufw enable || true
sudo ufw status numbered || true

echo "=== postgres role + db ==="
# Create/update role and database (idempotent-ish)
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_USER}') THEN
    CREATE ROLE ${POSTGRES_USER} LOGIN PASSWORD '${POSTGRES_PASSWORD}';
  ELSE
    ALTER ROLE ${POSTGRES_USER} WITH LOGIN PASSWORD '${POSTGRES_PASSWORD}';
  END IF;
END
\$\$;
SELECT 'CREATE DATABASE ${POSTGRES_DB} OWNER ${POSTGRES_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${POSTGRES_DB}')\gexec
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};
SQL

PG_MAJOR="$(ls /etc/postgresql 2>/dev/null | sort -V | tail -1 || true)"
if [[ -z "$PG_MAJOR" ]]; then
  echo "error: cannot find /etc/postgresql version dir" >&2
  exit 1
fi
PG_CONF="/etc/postgresql/${PG_MAJOR}/main/postgresql.conf"
PG_HBA="/etc/postgresql/${PG_MAJOR}/main/pg_hba.conf"

echo "=== postgres listen + hba (${PG_MAJOR}) ==="
sudo sed -i "s/^#\\?listen_addresses.*/listen_addresses = '*'/" "$PG_CONF"
# Ensure one scram line for app CIDR (strip old sinexis markers)
if ! sudo grep -q "sinexis-app-pg" "$PG_HBA"; then
  echo "host    ${POSTGRES_DB}    ${POSTGRES_USER}    ${APP_HOST_CIDR}    scram-sha-256  # sinexis-app-pg" | sudo tee -a "$PG_HBA" >/dev/null
fi
sudo systemctl enable postgresql
sudo systemctl restart postgresql

echo "=== redis ==="
# Ubuntu redis: /etc/redis/redis.conf
REDIS_CONF=/etc/redis/redis.conf
if [[ -f "$REDIS_CONF" ]]; then
  sudo sed -i 's/^bind .*/bind 0.0.0.0/' "$REDIS_CONF"
  sudo sed -i 's/^protected-mode yes/protected-mode yes/' "$REDIS_CONF"
  if sudo grep -q '^requirepass ' "$REDIS_CONF"; then
    sudo sed -i "s/^requirepass .*/requirepass ${REDIS_PASSWORD}/" "$REDIS_CONF"
  else
    echo "requirepass ${REDIS_PASSWORD}" | sudo tee -a "$REDIS_CONF" >/dev/null
  fi
  # Comment out default bind 127.0.0.1 if duplicated weirdly
  sudo systemctl enable redis-server
  sudo systemctl restart redis-server
else
  echo "error: $REDIS_CONF missing" >&2
  exit 1
fi

umask 077
cat > "$CRED_FILE" <<EOF
# Generated by bootstrap-data-host.sh — DO NOT commit. chmod 600.
# Copy values into app host .env / GitHub production secrets only.
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}
DATA_PUBLIC_HOST=${DATA_PUBLIC_HOST}
DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATA_PUBLIC_HOST}:5432/${POSTGRES_DB}
DATABASE_URL_SYNC=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATA_PUBLIC_HOST}:5432/${POSTGRES_DB}
REDIS_URL=redis://:${REDIS_PASSWORD}@${DATA_PUBLIC_HOST}:6379/0
CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@${DATA_PUBLIC_HOST}:6379/0
CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@${DATA_PUBLIC_HOST}:6379/0
EOF
chmod 600 "$CRED_FILE"

echo "=== local sanity ==="
sudo -u postgres psql -c 'SELECT 1' >/dev/null
redis-cli -a "$REDIS_PASSWORD" PING 2>/dev/null | grep -q PONG

echo "OK: Postgres + Redis listening; ufw allows $APP_HOST_CIDR on 5432/6379"
echo "Credentials written to $CRED_FILE (not printed). Fetch via scp from bastion only."
