import os
import shutil
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, File, Form, HTTPException, Query, UploadFile
from fastapi.responses import HTMLResponse, JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.schemas.scan import (
    DomainScanRequest,
    PaginatedResponse,
    ScanFindingResponse,
    ScanJobDetailResponse,
    ScanJobResponse,
    ScanRequest,
)
from app.services.scanner import ScannerService

router = APIRouter(tags=["scans"])
UPLOAD_DIR = "/tmp/scans"


def _export_json(job: ScanJobDetailResponse) -> dict:
    return {
        "scan_id": str(job.id),
        "scan_type": job.scan_type,
        "target": job.target,
        "status": job.status,
        "started_at": job.started_at.isoformat() if job.started_at else None,
        "completed_at": job.completed_at.isoformat() if job.completed_at else None,
        "duration_seconds": (job.completed_at - job.started_at).total_seconds() if job.started_at and job.completed_at else None,
        "summary": job.result_summary,
        "findings": [
            {
                "severity": f.severity,
                "category": f.category,
                "title": f.title,
                "description": f.description,
                "cve_id": f.cve_id,
                "cvss_score": f.cvss_score,
                "remediation": f.remediation,
                "raw_data": f.raw_data,
            }
            for f in job.findings
        ],
        "exported_at": datetime.now(timezone.utc).isoformat(),
    }


SEVERITY_COLOR_MAP = {"critical": "#dc2626", "high": "#f97316", "medium": "#eab308", "low": "#3b82f6", "info": "#6b7280"}
SEVERITY_ICON_MAP = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}

PDF_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
body {{ font-family: -apple-system, system-ui, sans-serif; background: #0a0a0a; color: #eee; padding: 40px; }}
h1 {{ color: #22c55e; border-bottom: 2px solid #333; padding-bottom: 10px; }}
h2 {{ color: #22c55e; margin-top: 30px; }}
table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
th {{ background: #1a1a1a; color: #22c55e; padding: 10px; text-align: left; }}
td {{ padding: 8px 10px; border-bottom: 1px solid #333; }}
.sev-critical {{ border-left: 4px solid #dc2626; }}
.sev-high {{ border-left: 4px solid #f97316; }}
.sev-medium {{ border-left: 4px solid #eab308; }}
.sev-low {{ border-left: 4px solid #3b82f6; }}
.sev-info {{ border-left: 4px solid #6b7280; }}
.badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }}
.badge-critical {{ background: #dc2626; color: #fff; }}
.badge-high {{ background: #f97316; color: #fff; }}
.badge-medium {{ background: #eab308; color: #000; }}
.badge-low {{ background: #3b82f6; color: #fff; }}
.badge-info {{ background: #6b7280; color: #fff; }}
.finding-row {{ margin: 5px 0; }}
.findings-array {{ margin: 20px 0; }}
p {{ margin: 5px 0; color: #aaa; }}
.footer {{ margin-top: 40px; text-align: center; color: #555; font-size: 12px; }}
</style></head><body>
<h1>Vulnerability Scan Report</h1>
<p><strong>Target:</strong> {target}</p>
<p><strong>Scan Type:</strong> {scan_type}</p>
<p><strong>Status:</strong> {status}</p>
<p><strong>Duration:</strong> {duration}</p>
<p><strong>Findings:</strong> {total_findings} total ({critical} critical, {high} high, {medium} medium, {low} low, {info} info)</p>
<p><strong>Exported:</strong> {exported_at}</p>

<h2>Findings</h2>
<table>
<tr><th>Severity</th><th>Category</th><th>Title</th><th>CVE</th><th>CVSS</th></tr>
{findings_rows}
</table>

<div class="footer">Generated by Vuln Scanner</div>
</body></html>"""


def _render_pdf_html(job: ScanJobDetailResponse) -> str:
    summary = job.result_summary or {}
    findings_rows = ""
    for f in job.findings:
        sev_class = f"sev-{f.severity}" if f.severity in ("critical", "high", "medium", "low", "info") else ""
        findings_rows += f"""
<tr class="{sev_class}">
  <td><span class="badge badge-{f.severity}">{f.severity.upper()}</span></td>
  <td>{f.category or ''}</td>
  <td>{f.title[:100]}</td>
  <td>{f.cve_id or ''}</td>
  <td>{f.cvss_score or ''}</td>
</tr>"""

    return PDF_TEMPLATE.format(
        target=job.target,
        scan_type=job.scan_type,
        status=job.status,
        duration=f"{(job.completed_at - job.started_at).total_seconds():.0f}s" if job.started_at and job.completed_at else "N/A",
        total_findings=summary.get("total_findings", 0),
        critical=summary.get("critical", 0),
        high=summary.get("high", 0),
        medium=summary.get("medium", 0),
        low=summary.get("low", 0),
        info=summary.get("info", 0),
        exported_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        findings_rows=findings_rows,
    )


@router.post("/scan/ip", response_model=ScanJobResponse, status_code=202)
async def start_ip_scan(req: ScanRequest, db: AsyncSession = Depends(get_db)):
    svc = ScannerService(db)
    job = await svc.start_scan(scan_type="ip", target=req.target, ports=req.ports)
    return job


@router.post("/scan/domain", response_model=ScanJobResponse, status_code=202)
async def start_domain_scan(req: DomainScanRequest, db: AsyncSession = Depends(get_db)):
    svc = ScannerService(db)
    job = await svc.start_scan(scan_type="domain", target=req.domain)
    return job


@router.post("/scan/mobile", response_model=ScanJobResponse, status_code=202)
async def start_mobile_scan(
    file: UploadFile = File(...),
    platform: str = Form(...),
    db: AsyncSession = Depends(get_db),
):
    if platform not in ("android", "ios"):
        raise HTTPException(status_code=400, detail="platform must be 'android' or 'ios'")
    if not file.filename:
        raise HTTPException(status_code=400, detail="File must have a filename")

    ext = ".apk" if platform == "android" else ".ipa"
    safe_name = os.path.basename(file.filename or f"upload{ext}")
    os.makedirs(UPLOAD_DIR, exist_ok=True)
    file_path = os.path.join(UPLOAD_DIR, f"{os.urandom(8).hex()}_{safe_name}")

    with open(file_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    try:
        scan_type = "apk" if platform == "android" else "ipa"
        svc = ScannerService(db)
        job = await svc.start_scan(scan_type=scan_type, target=file.filename, platform=platform, file_path=file_path)
        return job
    except Exception:
        try:
            os.remove(file_path)
        except Exception:
            pass
        raise


@router.get("/scan/history", response_model=PaginatedResponse)
async def get_scan_history(
    page: int = 1,
    limit: int = 20,
    scan_type: str | None = None,
    db: AsyncSession = Depends(get_db),
):
    svc = ScannerService(db)
    return await svc.get_history(page=page, limit=limit, scan_type=scan_type)


@router.get("/scan/{job_id}", response_model=ScanJobDetailResponse)
async def get_scan(job_id: str, db: AsyncSession = Depends(get_db)):
    svc = ScannerService(db)
    job = await svc.get_job(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Scan job not found")
    return job


@router.get("/scan/{job_id}/findings", response_model=list[ScanFindingResponse])
async def get_scan_findings(job_id: str, db: AsyncSession = Depends(get_db)):
    svc = ScannerService(db)
    findings = await svc.get_findings(job_id)
    return findings


@router.get("/scan/{job_id}/export")
async def export_scan(job_id: str, format: str = Query(default="json"), db: AsyncSession = Depends(get_db)):
    svc = ScannerService(db)
    job = await svc.get_job(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Scan job not found")

    if format == "json":
        result = _export_json(job)
        return JSONResponse(
            content=result,
            headers={"Content-Disposition": f'attachment; filename="scan_{job_id}.json"'},
        )

    if format == "html":
        html = _render_pdf_html(job)
        return HTMLResponse(content=html)

    raise HTTPException(status_code=400, detail="format must be 'json' or 'html'")
